# Generated by Django 2.2 on 2020-03-23 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='slogan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
