# Generated by Django 2.2.11 on 2020-03-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_carrito_itemcarrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='saludo',
            field=models.CharField(blank=True, default='Jaumina', max_length=20, null=True),
        ),
    ]
