# Generated by Django 2.2.11 on 2020-03-28 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_add_direccion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direccion',
            options={'verbose_name_plural': 'Direcciones'},
        ),
    ]
